#!/usr/bin/env python3
"""
evolution/generation_manager.py — Generation Lifecycle Controller
===================================================================
lolbot-HyperAI · Evolution Layer

The Generation Manager orchestrates the complete self-evolution cycle
from plan.md §二:

    Generation N (程序A)
      → Run session, collect logs
      → Evaluate fitness (看日志)
      → Generate mutation proposals (修复酶)
      → Apply mutations → Generation N+1 (程序A')
      → Run session with A', evaluate fitness
      → If fitness(A') > fitness(A): commit
      → Else: rollback to A

This is the "while True" loop at the highest level — each game session
is one iteration of the evolution loop.

State management:
    - Each generation has a unique ID and a snapshot of all tunable params
    - Snapshots are stored as JSON files in data/generations/
    - The "current" symlink points to the active generation
    - Rollback = point "current" back to the previous generation

Tunable parameters (what mutations can change):
    - Win probability model weights
    - Recommendation cooldowns
    - Confidence thresholds
    - Announcement intervals
    - Feature normalization ranges

Publishes to: CH_EVOLUTION_GENERATION
"""

from __future__ import annotations

import copy
import hashlib
import json
import os
import shutil
import sys
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).parent.parent))
from canbus.channel_message import (
    CH_EVOLUTION_GENERATION,
    MessageFactory,
)
from canbus.transport import Transport


# ---------------------------------------------------------------------------
# Generation snapshot
# ---------------------------------------------------------------------------
@dataclass
class GenerationSnapshot:
    """
    Complete snapshot of all tunable parameters for one generation.

    This is what gets saved to disk and what mutations operate on.
    """
    generation_id: str = ""
    parent_id: Optional[str] = None
    created_at: str = ""
    mutation_description: str = ""

    # Win probability model weights
    prediction_weights: Dict[str, float] = field(default_factory=dict)
    prediction_bias: float = 0.0

    # Recommendation cooldowns (RecType → seconds)
    recommendation_cooldowns: Dict[str, float] = field(default_factory=dict)

    # Thresholds
    min_recommendation_confidence: float = 0.4
    min_announce_interval_sec: float = 5.0
    win_update_interval_sec: float = 60.0

    # Feature pipeline params
    feature_normalization: Dict[str, Tuple[float, float]] = field(
        default_factory=dict
    )

    # Fitness history
    fitness_scores: List[Dict[str, Any]] = field(default_factory=list)
    avg_fitness: float = 0.0
    sessions_evaluated: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "GenerationSnapshot":
        # Handle tuple conversion for feature_normalization
        fn = data.get("feature_normalization", {})
        if fn:
            data["feature_normalization"] = {
                k: tuple(v) if isinstance(v, list) else v
                for k, v in fn.items()
            }
        return cls(**{
            k: v for k, v in data.items()
            if k in cls.__dataclass_fields__
        })

    def clone(self) -> "GenerationSnapshot":
        """Deep copy for creating child generations."""
        return GenerationSnapshot.from_dict(copy.deepcopy(self.to_dict()))


# ---------------------------------------------------------------------------
# Mutation proposal
# ---------------------------------------------------------------------------
@dataclass
class MutationProposal:
    """
    A proposed change to the system parameters.

    Generated by the strategy_mutator (LLM-based or rule-based).
    """
    proposal_id: str
    category: str               # "weight_adjustment", "cooldown_tuning",
                                # "threshold_change", "new_feature"
    target_param: str           # e.g. "prediction_weights.gold_diff_norm"
    old_value: Any
    new_value: Any
    rationale: str
    confidence: float = 0.5
    estimated_impact: str = "medium"  # "low", "medium", "high"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "category": self.category,
            "target_param": self.target_param,
            "old_value": self.old_value,
            "new_value": self.new_value,
            "rationale": self.rationale,
            "confidence": self.confidence,
            "estimated_impact": self.estimated_impact,
        }


# ---------------------------------------------------------------------------
# Generation Manager
# ---------------------------------------------------------------------------
class GenerationManager:
    """
    Manages the generation lifecycle.

    Responsibilities:
        1. Load/save generation snapshots
        2. Apply mutations to create new generations
        3. Track fitness across sessions
        4. Commit or rollback generations
        5. Maintain generation history

    Directory structure:
        data/generations/
            gen_001_abc123/
                snapshot.json
                fitness_history.json
                mutations_applied.json
            gen_002_def456/
                ...
            current -> gen_002_def456  (symlink)
    """

    MAX_GENERATIONS = 50  # Keep last 50 generations

    def __init__(
        self,
        transport: Transport,
        data_dir: Path,
    ) -> None:
        self._transport = transport
        self._factory = MessageFactory("evolution.generation_manager")
        self._data_dir = data_dir / "generations"
        self._data_dir.mkdir(parents=True, exist_ok=True)

        self._current: Optional[GenerationSnapshot] = None
        self._generation_count = 0

    # -- Lifecycle ------------------------------------------------------

    def init(self) -> GenerationSnapshot:
        """
        Load the current generation, or create the initial one.

        Returns the active generation snapshot.
        """
        current_link = self._data_dir / "current"

        if current_link.exists():
            # Load existing
            target = current_link.resolve()
            snapshot_path = target / "snapshot.json"
            if snapshot_path.exists():
                data = json.loads(snapshot_path.read_text())
                self._current = GenerationSnapshot.from_dict(data)
                self._generation_count = self._count_generations()
                return self._current

        # Create initial generation
        self._current = self._create_initial()
        self._save_generation(self._current)
        self._update_current_link(self._current.generation_id)
        self._generation_count = 1
        return self._current

    def _create_initial(self) -> GenerationSnapshot:
        """Create the generation-zero snapshot with default params."""
        from prediction.win_probability_engine import LogisticModel
        from planning.strategy_planner import CooldownManager

        model = LogisticModel()
        cooldowns = CooldownManager()

        gen_id = self._make_id(0)
        return GenerationSnapshot(
            generation_id=gen_id,
            parent_id=None,
            created_at=datetime.now(timezone.utc).isoformat(),
            mutation_description="Initial generation (defaults)",
            prediction_weights=dict(model.weights),
            prediction_bias=model.bias,
            recommendation_cooldowns=cooldowns.export(),
            min_recommendation_confidence=0.4,
            min_announce_interval_sec=5.0,
            win_update_interval_sec=60.0,
        )

    # -- Mutation application -------------------------------------------

    def apply_mutations(
        self,
        proposals: List[MutationProposal],
    ) -> GenerationSnapshot:
        """
        Apply a list of mutation proposals to create a new generation.

        Returns the new (uncommitted) generation snapshot.
        The caller should evaluate its fitness before committing.
        """
        if self._current is None:
            raise RuntimeError("No current generation. Call init() first.")

        # Clone current generation
        new_gen = self._current.clone()
        new_gen.parent_id = self._current.generation_id
        self._generation_count += 1
        new_gen.generation_id = self._make_id(self._generation_count)
        new_gen.created_at = datetime.now(timezone.utc).isoformat()
        new_gen.fitness_scores = []
        new_gen.avg_fitness = 0.0
        new_gen.sessions_evaluated = 0

        # Apply each mutation
        descriptions = []
        for proposal in proposals:
            self._apply_single_mutation(new_gen, proposal)
            descriptions.append(
                f"{proposal.category}: {proposal.target_param} "
                f"({proposal.old_value} → {proposal.new_value})"
            )

        new_gen.mutation_description = "; ".join(descriptions)

        # Save but don't make current yet
        self._save_generation(new_gen)
        self._save_mutations(new_gen.generation_id, proposals)

        return new_gen

    def _apply_single_mutation(
        self,
        snapshot: GenerationSnapshot,
        proposal: MutationProposal,
    ) -> None:
        """Apply a single mutation to a snapshot."""
        target = proposal.target_param

        if target.startswith("prediction_weights."):
            feature = target.split(".", 1)[1]
            snapshot.prediction_weights[feature] = proposal.new_value

        elif target == "prediction_bias":
            snapshot.prediction_bias = proposal.new_value

        elif target.startswith("recommendation_cooldowns."):
            rec_type = target.split(".", 1)[1]
            snapshot.recommendation_cooldowns[rec_type] = proposal.new_value

        elif target == "min_recommendation_confidence":
            snapshot.min_recommendation_confidence = proposal.new_value

        elif target == "min_announce_interval_sec":
            snapshot.min_announce_interval_sec = proposal.new_value

        elif target == "win_update_interval_sec":
            snapshot.win_update_interval_sec = proposal.new_value

    # -- Fitness tracking -----------------------------------------------

    def record_fitness(
        self,
        generation_id: str,
        fitness_data: Dict[str, Any],
    ) -> None:
        """Record a fitness evaluation for a generation."""
        gen_dir = self._data_dir / generation_id
        history_path = gen_dir / "fitness_history.json"

        history = []
        if history_path.exists():
            try:
                history = json.loads(history_path.read_text())
            except json.JSONDecodeError:
                history = []

        fitness_data["recorded_at"] = datetime.now(timezone.utc).isoformat()
        history.append(fitness_data)

        history_path.write_text(json.dumps(history, indent=2))

        # Update snapshot
        if self._current and self._current.generation_id == generation_id:
            self._current.fitness_scores.append(fitness_data)
            self._current.sessions_evaluated += 1
            scores = [
                d.get("total_fitness", 0)
                for d in self._current.fitness_scores
            ]
            self._current.avg_fitness = sum(scores) / len(scores)

    # -- Commit / Rollback ----------------------------------------------

    def commit(self, generation_id: str) -> bool:
        """
        Commit a generation: make it the current active generation.

        Returns True if committed successfully.
        """
        gen_dir = self._data_dir / generation_id
        if not gen_dir.exists():
            return False

        snapshot_path = gen_dir / "snapshot.json"
        if not snapshot_path.exists():
            return False

        data = json.loads(snapshot_path.read_text())
        self._current = GenerationSnapshot.from_dict(data)
        self._update_current_link(generation_id)

        # Publish generation transition
        msg = self._factory.create(
            CH_EVOLUTION_GENERATION,
            {
                "action": "commit",
                "generation_id": generation_id,
                "parent_id": self._current.parent_id,
                "mutation": self._current.mutation_description,
                "avg_fitness": self._current.avg_fitness,
            },
        )
        self._transport.publish(msg)

        # Prune old generations
        self._prune_old_generations()

        return True

    def rollback(self) -> Optional[str]:
        """
        Rollback to the parent generation.

        Returns the parent generation ID, or None if at root.
        """
        if self._current is None or self._current.parent_id is None:
            return None

        parent_id = self._current.parent_id
        parent_dir = self._data_dir / parent_id
        if not parent_dir.exists():
            return None

        data = json.loads((parent_dir / "snapshot.json").read_text())
        self._current = GenerationSnapshot.from_dict(data)
        self._update_current_link(parent_id)

        msg = self._factory.create(
            CH_EVOLUTION_GENERATION,
            {
                "action": "rollback",
                "generation_id": parent_id,
                "rolled_back_from": self._current.generation_id,
            },
        )
        self._transport.publish(msg)

        return parent_id

    def should_commit(
        self,
        new_fitness: float,
        old_fitness: float,
        threshold: float = 0.01,
    ) -> bool:
        """
        Decide whether to commit a new generation.

        Conservative policy: only commit if new fitness exceeds
        old fitness by at least `threshold`.
        """
        return new_fitness > old_fitness + threshold

    # -- Persistence ----------------------------------------------------

    def _save_generation(self, snapshot: GenerationSnapshot) -> None:
        """Save a generation snapshot to disk."""
        gen_dir = self._data_dir / snapshot.generation_id
        gen_dir.mkdir(parents=True, exist_ok=True)
        path = gen_dir / "snapshot.json"
        path.write_text(json.dumps(snapshot.to_dict(), indent=2, default=str))

    def _save_mutations(
        self,
        generation_id: str,
        proposals: List[MutationProposal],
    ) -> None:
        """Save mutation proposals for auditing."""
        gen_dir = self._data_dir / generation_id
        path = gen_dir / "mutations_applied.json"
        path.write_text(json.dumps(
            [p.to_dict() for p in proposals], indent=2,
        ))

    def _update_current_link(self, generation_id: str) -> None:
        """Update the 'current' symlink to point to the given generation."""
        link = self._data_dir / "current"
        target = self._data_dir / generation_id

        if link.exists() or link.is_symlink():
            link.unlink()

        try:
            link.symlink_to(target)
        except OSError:
            # On Windows, symlinks may fail — write a marker file instead
            link.write_text(generation_id)

    def _count_generations(self) -> int:
        """Count existing generation directories."""
        return sum(
            1 for p in self._data_dir.iterdir()
            if p.is_dir() and p.name.startswith("gen_")
        )

    def _prune_old_generations(self) -> None:
        """Remove old generations beyond MAX_GENERATIONS."""
        gen_dirs = sorted(
            [p for p in self._data_dir.iterdir()
             if p.is_dir() and p.name.startswith("gen_")],
            key=lambda p: p.stat().st_mtime,
        )
        while len(gen_dirs) > self.MAX_GENERATIONS:
            oldest = gen_dirs.pop(0)
            # Don't prune the current generation
            if self._current and oldest.name == self._current.generation_id:
                continue
            shutil.rmtree(oldest, ignore_errors=True)

    # -- Helpers --------------------------------------------------------

    @staticmethod
    def _make_id(index: int) -> str:
        """Generate a generation ID."""
        ts = int(time.time())
        raw = f"gen_{index}_{ts}"
        suffix = hashlib.md5(raw.encode()).hexdigest()[:6]
        return f"gen_{index:04d}_{suffix}"

    # -- Public API -----------------------------------------------------

    @property
    def current(self) -> Optional[GenerationSnapshot]:
        return self._current

    @property
    def generation_count(self) -> int:
        return self._generation_count

    def get_generation(self, gen_id: str) -> Optional[GenerationSnapshot]:
        """Load a specific generation from disk."""
        path = self._data_dir / gen_id / "snapshot.json"
        if not path.exists():
            return None
        data = json.loads(path.read_text())
        return GenerationSnapshot.from_dict(data)

    def list_generations(self) -> List[Dict[str, Any]]:
        """List all generations with summary info."""
        result = []
        for p in sorted(self._data_dir.iterdir()):
            if not p.is_dir() or not p.name.startswith("gen_"):
                continue
            snap_path = p / "snapshot.json"
            if snap_path.exists():
                try:
                    data = json.loads(snap_path.read_text())
                    result.append({
                        "id": data.get("generation_id", p.name),
                        "parent": data.get("parent_id"),
                        "created": data.get("created_at"),
                        "mutation": data.get("mutation_description", ""),
                        "avg_fitness": data.get("avg_fitness", 0),
                        "sessions": data.get("sessions_evaluated", 0),
                        "is_current": (
                            self._current is not None
                            and data.get("generation_id") == self._current.generation_id
                        ),
                    })
                except json.JSONDecodeError:
                    pass
        return result

    def stats(self) -> Dict[str, Any]:
        return {
            "current_generation": (
                self._current.generation_id if self._current else None
            ),
            "generation_count": self._generation_count,
            "current_avg_fitness": (
                self._current.avg_fitness if self._current else 0
            ),
            "current_sessions": (
                self._current.sessions_evaluated if self._current else 0
            ),
        }
