# Copyright (c) Microsoft. All rights reserved.

from __future__ import annotations

import logging
import os
import warnings
from typing import Any, List

import vllm.entrypoints.openai.protocol
from vllm.entrypoints.openai.protocol import ChatCompletionResponse
from vllm.entrypoints.openai.serving_chat import OpenAIServingChat

__all__ = [
    "instrument_vllm",
    "uninstrument_vllm",
    "is_neuron_device",
]

logger = logging.getLogger(__name__)


# === M30: vLLM-Neuron 设备检测 (命题3: HTTP身体 → Neuron硬件) ===
def is_neuron_device() -> bool:
    """
    检测当前是否运行在AWS Trainium/Inferentia设备上。
    
    Returns:
        True: 如果检测到Neuron设备
        False: 否则
    """
    # 检查 /dev/neuron* 设备
    if os.path.exists("/dev/neuron0"):
        return True
    
    # 检查 NEURON_RT_VISIBLE_CORES 环境变量
    if os.environ.get("NEURON_RT_VISIBLE_CORES"):
        return True
    
    # 尝试导入 torch_neuronx
    try:
        import torch_neuronx  # noqa: F401
        return True
    except ImportError:
        pass
    
    return False


class ChatCompletionResponsePatched(ChatCompletionResponse):
    prompt_token_ids: List[int] | None = None
    response_token_ids: List[int] | None = None


original_chat_completion_full_generator = OpenAIServingChat.chat_completion_full_generator


async def chat_completion_full_generator(
    self: Any,
    request: Any,
    result_generator: Any,
    request_id: str,
    model_name: str,
    conversation: Any,
    tokenizer: Any,
    request_metadata: Any,
) -> Any:
    prompt_token_ids: List[int] | None = None
    response_token_ids: List[List[int]] | None = None

    async def _generate_inceptor():
        nonlocal prompt_token_ids, response_token_ids
        async for res in result_generator:
            yield res
            prompt_token_ids = res.prompt_token_ids
            response_token_ids = [output.token_ids for output in res.outputs]

    response = await original_chat_completion_full_generator(
        self,
        request,
        _generate_inceptor(),
        request_id,
        model_name,
        conversation,
        tokenizer,
        request_metadata,
    )
    response = response.model_copy(
        update={
            "prompt_token_ids": prompt_token_ids,
            "response_token_ids": response_token_ids,
        }
    )

    return response


def instrument_vllm():
    """Instrument vLLM to capture token IDs generated by engine.

    This instrumentation has been merged to upstream vLLM since v0.10.2.
    
    === M30: vLLM-Neuron 支持说明 ===
    
    当运行在AWS Trainium/Inferentia设备上时:
    - 使用 vLLM-Neuron 替代标准 vLLM
    - Token ID 捕获可能需要额外配置
    - 建议使用 neuronx-cc 编译模型以获得最佳性能
    
    环境变量配置:
    - NEURON_RT_VISIBLE_CORES: 可见的Neuron Core列表
    - NEURON_CC_FLAGS: 编译器标志
    - XLA_USE_BF16: 启用BF16混合精度
    """
    if vllm.entrypoints.openai.protocol.ChatCompletionResponse is ChatCompletionResponsePatched:
        warnings.warn("vllm is already instrumented. Skip the instrumentation.")
        return
    
    # === M30: 检测并记录设备类型 ===
    if is_neuron_device():
        logger.info("Neuron device detected. vLLM instrumentation will use Neuron-compatible mode.")
        # 在Neuron设备上，确保XLA优化启用
        os.environ.setdefault("XLA_USE_BF16", "1")
    else:
        logger.debug("Standard vLLM instrumentation (CUDA/CPU mode).")

    vllm.entrypoints.openai.protocol.ChatCompletionResponse = ChatCompletionResponsePatched
    OpenAIServingChat.chat_completion_full_generator = chat_completion_full_generator


def uninstrument_vllm():
    """Uninstrument vLLM to stop capturing token IDs generated by engine."""
    OpenAIServingChat.chat_completion_full_generator = original_chat_completion_full_generator
